### ISSUE TITLE
Can't generate TOC 

### ISSUE THREAD

**Issue by manhnt9** [lwchkg/gitbook-pdfgen#7]
I use vbnet_intro.zip from [here](https://github.com/GitbookIO/gitbook/issues/1470) and try generate pdf, the TOC page only has a title.

**Comment by lwchkg** [comment]
Don't use WKHTMLToPDF 0.12.5 to generate the PDF. It is known not to work.
Use either 0.12.4 or the newest dev version.

**Comment by manhnt9** [comment]
Works great with  0.12.4. Thank you!
